[package]
name = "passgen_adapter"
version = "3.1.0"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[lib]
name = "passgen_adapter"
crate-type = ["staticlib"]

[dependencies]
libpassgen = { path = "../libpassgen" }
